version: "3.8"
services:
  server:
    build: ./server
    container_name: node-api
    restart: always
    ports:
      - "3300:3300"
    env_file:
      - .env 
    volumes:
      - logs:/app/logs
      - data:/app/data
      - node_modules:/app/node_modules
    networks:
      - todo-network

  client:
    build: ./client
    container_name: react-ui
    ports:
      - "3000:3000"
    volumes:
      - src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - server
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge

volumes:
  logs:
  data:
  node_modules:
  src:

